# Get the key to encrypt data
- name: "Get the key to encrypt data"
  shell: "docker exec -it vault-container sh -c \"export VAULT_ADDR=http://127.0.0.1:25355 && vault read -field code backup/key\""
  become: yes
  register: cryptkey