- name: "Load key to unseal vault"
  set_fact: firstkey="{{ lookup('file','/etc/ansible/ssh_keys/'+deploystage+'_vault/firstkey') }}"

- name: "Load key to unseal vault"
  set_fact: secondkey="{{ lookup('file','/etc/ansible/ssh_keys/'+deploystage+'_vault/secondkey') }}"

- name: "Load key to unseal vault"
  set_fact: thirdkey="{{ lookup('file','/etc/ansible/ssh_keys/'+deploystage+'_vault/thirdkey') }}"

- name: "Load Token Ansible user"
  set_fact: ansible_user_vault="{{ lookup('file','/etc/ansible/ssh_keys/'+deploystage+'_vault/ansibletoken') }}"

- name: "Unseal the Vault using the first key"
  shell: "docker exec -it vault-container sh -c \"export VAULT_ADDR=http://127.0.0.1:25355 && vault operator unseal {{ firstkey }} \""
  become: yes
  no_log: true

- name: "Unseal the Vault using the second key"
  shell: "docker exec -it vault-container sh -c \"export VAULT_ADDR=http://127.0.0.1:25355 && vault operator unseal {{ secondkey }} \""
  become: yes
  no_log: true

- name: "Unseal the Vault using the third key"
  shell: "docker exec -it vault-container sh -c \"export VAULT_ADDR=http://127.0.0.1:25355 && vault operator unseal {{ thirdkey }} \""
  become: yes
  no_log: true

- name: "Wait for 5 sec"
  pause:
    seconds: 5

- name: "Login as Ansible user"
  shell: "docker exec -it vault-container sh -c \"export VAULT_ADDR=http://127.0.0.1:25355 && vault login {{ ansible_user_vault }} \""
  become: yes
  no_log: true